version: "3.9"

services:
  adp_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adp_frontend
    ports:
      - "8080:80"
    networks:
      - adp_net
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: "production"
      MEILI_MASTER_KEY: "supersecretkey1234567890"
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meili_data:/meili_data
    networks:
      - adp_net
    restart: unless-stopped

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: etl
    networks:
      - adp_net
    volumes:
      - ./etl:/app
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_API_KEY=supersecretkey1234567890
    depends_on:
      - meilisearch
    tty: true
    stdin_open: true
    command: ["/bin/bash"]

volumes:
  meili_data:

networks:
  adp_net:
